name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop --command just install
      - run: nix develop --command just check

  publish:
    needs: check
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop --command just install
      - run: nix develop --command just publish
    env:
      ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
      ROBLOX_PLACE_ID: ${{ secrets.ROBLOX_PLACE_ID }}
